version: '3.7'

services:
  mysql-db:
    image: mysql:8.1
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - local-mysql.env
    restart: unless-stopped
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
